project:
  base_path: .

test_settings:
  max_files: 0  # Use all available files
  thresholds: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

models:
  silero:
    wrapper: src.wrappers.vad_silero
    vad_type: probabilistic  
    enabled: true
    
  webrtc:
    wrapper: src.wrappers.vad_webrtc
    enabled: true
    
  ast:
    wrapper: src.wrappers.vad_ast
    vad_type: probabilistic
    enabled: true
    
  epanns:
    wrapper: src.wrappers.vad_epanns
    vad_type: probabilistic
    enabled: true
    
  panns:
    wrapper: src.wrappers.vad_panns
    vad_type: probabilistic
    enabled: true
    
  passt:
    wrapper: src.wrappers.vad_passt
    vad_type: probabilistic
    enabled: true

scenarios:
  chime_cmfv:
    description: "CHiME-Home: Broad vocal content detection (CMFV) - Paper reproduction"
    chunks_path: datasets/chime/chunks_subset5
    ground_truth: ground_truth/chime/cmfv.csv
